### ISSUE TITLE
no translation for icons v2.0

### ISSUE THREAD

**Issue by igumen1990** [danjono/InventoryRollback#46]
there is no translation string for icons in the new version. in the config of the old version (1.4) there was this:
```
icons:
  mainMenu:
    deathIcon:
      item: BONE
      name: '&cСмерти'
    joinIcon:
      item: OAK_SAPLING
      name: '&aВходы в игру'
    quitIcon:
      item: RED_BED
      name: '&6Выходы из игры'
    worldChangeIcon:
      item: COMPASS
      name: '&eСмена мира'
    forceSaveIcon:
      item: DIAMOND
      name: '&bForce Saves'
```
the new one doesn't
